### ISSUE TITLE
Subdomain - Cache and Remote Cache Issues

### ISSUE THREAD

**Issue by davidpede** [modxcms/pThumb#18]
PROBLEM 1 - I am trying to impliment pThumb using a image subdomain and am having issues with the cache path.

My subdomain Setup:
I have all images stored in a folder: /home/foo/public_html/img
This folder is accessed via a subdomain: http://img.foo.co.uk
I have setup a mediasource for this folder and have applied to the relevant image tv's.
I am accessing these images from these domains:
  http://www.foo.co.uk
  http://cn.foo.co.uk
  http://ru.foo.co.uk
The above all works correctly.

pThumb Setup:
  I apply pThumb to the tpl's: [[+tv.team-member-photo:pthumb=`&w=100&h=100`]]
Settings:
  phpthumbof.cache_url: http://img.foo.co.uk/
  pthumb.ptcache_images_basedir: img
  pthumb.ptcache_location: img/cache
  phpthumbof.use_resizer: Yes

The image url should display as:
  http://img.foo.co.uk/cache/web/staff-photos/someone.2e0d42c8.jpg

Instead it displays as:
  http://img.foo.co.uk/img/cache/web/staff-photos/someone.2e0d42c8.jpg

This results with broken links. The only way I can fix is by adding a .htaccess file to the '/home/foo/public_html/img' folder that rewrites as following:
  RewriteEngine On
  RewriteBase /
  RewriteRule ^img/cache/(.*)$ cache/$1 [L,NE,R=301]

The image url still shows as:
  http://img.foo.co.uk/img/cache/web/staff-photos/someone.2e0d42c8.jpg
but the images now display. This works accross all my domains (http://www.foo.co.uk, http://cn.foo.co.uk, http://ru.foo.co.uk)

How can I do this so don't need the .htaccess rewrite?

PROBLEM 2 - Also, pThumb is creating images in a remote cache folder:
/home/foo/public_html/assets/components/phpthumbof/cache/remote-images/img.foo.co.uk/

This shouldn't be the case, how do I stop this?

Thanks

**Comment by davidpede** [comment]
Regarding PROBLEM 2 - after some more investigation it seems that pthumb is copying all the original images
from:
  /home/foo/public_html/img
to:
  /home/foo/public_html/assets/components/phpthumbof/cache/remote-images/img.foo.co.uk/
and then creating the cached versions
here:
  /home/foo/public_html/img/cache

Shouldn't it have realised that the images are on the same server? Do I need to setup a context in MODX?

**Comment by oo12** [comment]
Problem 1:
What if you set pthumb.ptcache_location to cache instead of img/cache?  That would put the thumbnail URLs into the format you want.
Although... I think the source of the confusion is that it's writing the thumbnail to /img/cache/web/staff-photos/someone.2e0d42c8.jpg _on the site where pThumb is called_.  Since you have phpthumbof.cache_url set to some URL it's prepending that to the thumbnail path, without any further thought.  It's not saving the thumbnail back to img.foo.co.uk, since that could be an entirely different server.  If you clear out the phpthumbof.cache_url setting, then you don't get broken images right?

Problem 2:
If you give pThumb a URL like http://img.foo.co.uk/img/something.jpg it will compare img.foo.co.uk with the value of MODX_HTTP_HOST.  If they're the same then it will figure out it's actually a local file.  If they're different though, pThumb will treat it as a remote image.  Now, img.foo.co.uk and www.foo.co.uk _could_ be the same server, but establishing that is a little trickier and the file would still have to be accessed via the URL instead of directly on the file system since we wouldn't know the path and PHP may not have read access for it anyway.

If the files are on the same server, you could give it a path to the file ( /home/foo/public_html/img/something.jpg or maybe img/something.jpg depending on how you have your directories set up). Then it wouldn't treat it as a remote image.

I think you could fix all this with contexts; that's probably the way to go.

**Comment by davidpede** [comment]
PROBLEM 1: Thanks for your response. I have tried your ideas but am still struggling.

"What if you set pthumb.ptcache_location to cache instead of img/cache? That would put the thumbnail URLs into the format you want."
Doesn't work. The image urls change to the source location and when I clear the cache I get an error in the console: [pThumb] Cache path not writable: /home/foo/public_html/cache/.
(Its not writable as it doesn't exist)

"If you clear out the phpthumbof.cache_url setting, then you don't get broken images right?"
Correct

I think the main problem is that I need pthumb to realise that /img/cache is the path to the cache folder but to serve http://img.foo.co.uk/cache as the url. Is this possible?

Thanks again

**Comment by davidpede** [comment]
PROBLEM 2: I have been experimenting with this issue as well.

"If the files are on the same server, you could give it a path to the file ( /home/foo/public_html/img/something.jpg or maybe img/something.jpg depending on how you have your directories set up). Then it wouldn't treat it as a remote image."

I see what you mean. The image tv I am passing to pthumb uses a mediasource that has 'http://img.foo.co.uk' as its 'baseUrl'. Removing this and pthumb treats it as local. However, I need the 'baseUrl' to remain as 'http://img.foo.co.uk'.

"it will compare img.foo.co.uk with the value of MODX_HTTP_HOST. If they're the same then it will figure out it's actually a local file."

I have tried adding a context for the 'http://img.foo.co.uk' subdomain and adding a 'http_host' context setting that matches the web context. Has no effect.

"I think you could fix all this with contexts; that's probably the way to go"

Could you elaborate? Not sure what I settings I need to add to the context to get this working.

Thanks

**Comment by oo12** [comment]
Problem 1:  I think if you manually create /home/foo/public_html/cache and make it writable for PHP, then this should work.  You're probably not using FCGI as your PHP handler, so PHP is running as another user, not the owner of the files. You may need to make the directory world writable.

Problem 2:  I need to change one thing in order for a 'http_host' context setting to have an effect.  If you'd like to test it, find [line 163](https://github.com/oo12/phpThumbOf/blob/351888de2946ff687249cce4eeda18f0a1b8f260/core/components/phpthumbof/model/phpthumbof.class.php#L163) in core/components/phpthumbof/model/phpthumbof.class.php and replace `MODX_HTTP_HOST` with  `$this->modx->getOption('http_host')`

As far as context settings, I'm not sure exactly how to set that up properly; it depends some on how you're handling routing for them.  I haven't used contexts but a couple times and I'm no expert on them.  This does seem like something you'd want to use them for though.

**Comment by oo12** [comment]
This should work better now in 2.3.1.
