### ISSUE TITLE
Output dataURIs instead of paths

### ISSUE THREAD

**Issue by exside** [modxcms/pThumb#19]
It would be nice if there was an option like &datauri=`1` which would output a base64 encoded data source of the generated thumbnail instead of the direct path (to reduce requests) with a check included for old IEs (IE5-8) that do not support dataURIs fully (IE8 up to 32kb, but not more...) and if detected the normal path should be returned. If there is motivation around to also support IE8, there could be a check of the thumbnails filesize and if it's smaller than 32kb it can be encoded for IE8 too.

This can be a stupid preg_match check for user agent, I think this should be enough, even if not completely reliable:

```
// 3-8 because if we take 1-8 it also catches IE10/11, could also be 5-8
preg_match('#(?i)msie [3-8]#', strtolower($_SERVER['HTTP_USER_AGENT']));
```

Maybe a second property like datauriMaxSize=`32768` (in bytes) could also be included to not have all pictures encoded (as particularely big ones are a huge bloat to the html).

The generated dataURI strings should also be cached as it can generate quite some load if done with each request.

If I find some time I'll fiddle around with the possibilities, so this issue is not just a "request" but also a reminder for myself =)

thanks for your great work with this extra!

**Comment by oo12** [comment]
I think a feature like this would be more versatile as a separate output filter, since it could then work with things like svg, or directly with an image without running it through pThumb.  For instance `[[*imagetv:pthumb=`w=150`:datauri]]` or just `[[*sometv:datauri]]`.

However, while using a data URI can save one HTTP request over a separate image (assuming the image isn't already cached by the visitor's browser), I'm a little dubious on the performance benefits of doing this generally.  Consider:
- Data URIs can't have their own cache policy.  If they're embedded in HTML (CSS is a better idea) then whenever the page changes they all have to be downloaded again.  Standard images can have a far future Expires header so once they're cached they don't require any further HTTP requests, even if the page they're on changes.
- If the same image is encoded in a data uri and used on multiple pages, it has to be downloaded together with _each_ page.
- Images are 37% larger due to base64 encoding. (though gzip encoding would mitigate the size increase to an extent)
- They materialize considerably [slower](http://www.mobify.com/blog/data-uris-are-slow-on-mobile/) on mobile devices, especially older ones.

**Comment by exside** [comment]
yeah, agree with closing this =)
