### ISSUE TITLE
image height no longer reliably what I requested

### ISSUE THREAD

**Issue by watou** [modxcms/pThumb#5]
I had been using pThumb 2.0.0-pl with no visible problems -- different-sized images that fit within a 1024 box were being resized to 240 w X 360 h every time I passed them to the output modifier:

```
[[+image:phpThumbOf=`w=240&h=360`]]
```

I would always get white borders as needed.  But since I've upgraded to 2.1.0-pl2 from 2.0.0-pl, I now see the occasion failure, where the image is always 240 wide as expected, but the height is sometimes relative to the original width, instead of sized to the proper height with white borders added as needed.  The original phpThumbOf also handled `w=240&h=360` correctly every time before I upgraded to your replacement.

![image](https://f.cloud.github.com/assets/3008217/1491413/1b27c130-47ae-11e3-98f5-d52f3e4024d3.png)

I've cleared the cache repeatedly and there are no log messages.  This is MODX 2.2.10-pl.  I use imageSlim (latest available) elsewhere but not on this content.

Thanks very much if you can take a look at this apparent regression!

Regards, watou

**Comment by watou** [comment]
To clarify, without the &far=c option, the source images used to produce 240x360 images every time, however now the far=c option is required to get this reliably where it wasn't before.  If far=c is required now but wasn't before or with the original phpThumbOf, then this would mean there is a semantic difference from the original snippet.  (You may therefore view this as either a bug or not a bug, depending on whether you care about strict compatibility with phpThumbOf's options.)

**Comment by oo12** [comment]
The difference is, between 2.0 and 2.1 I switched from using the modPhpThumb class to using phpThumb directly.  modPhpThumb extends phpThumb; basically it retrieves all the settings from core > phpThumb then passes them to phpThumb, which does the actual work.  Have a look [here](https://github.com/modxcms/revolution/blob/develop/core/model/phpthumb/modphpthumb.class.php#L28-L66).

The way phpThumb is written though, you have to instantiate a new object for each image you want to create.  It's not efficient when you have multiple images.  If there are 20 images on a page, it has to do all that business with the settings 20 times, even though the settings are the same each time.  The majority of those settings aren't relevant to what pThumb is doing anyway, so skipping them makes things go that much faster.  With a lot of images on a page, it makes enough of a speed difference to be worth it (I think).

_However_ as you can see one of those settings happens to be `far`!  So with phpThumbOf and pThumb < 2.1 there was an implicit `far=C` being added to each of your images ([line 54](https://github.com/modxcms/revolution/blob/develop/core/model/phpthumb/modphpthumb.class.php#L54)).  Starting with pThumb 2.1, to improve phpThumb performance there aren't any default settings added, so you need to add it yourself.  (You'd need to add it for Resizer anyway, since it never got any of these system settings.)

I'll admit though, I hadn't thought of this side effect!  I'll put something about it in the documentation.

**Comment by oo12** [comment]
I'm thinking about instead of a 'default quality' system setting having a 'default options string' setting, which would be more versatile since you could add options besides just jpeg quality.  You could put `far=C` in there and be back to the good ol' days :-)

**Comment by watou** [comment]
Thanks for the perfectly clear explanation of what changed and why, and for the idea of exposing a default options string in the properties.  For now, adding `&far=c` got me back to the old behaviour, but having that as a global option so pThumb can semantically match old phpthumbof behaviour without requiring changes to elements or resources, sounds like a great idea.

**Comment by oo12** [comment]
I came up with a "have your cake and eat it too" solution for this I think. pThumb will now use those MODX system settings for phpThumb—far and a few others—and with a negligible effect on performance.  In fact it may even be a hair faster now in certain cases thanks to some other changes in the commit above.

**Comment by watou** [comment]
Very cool!  Thanks.

**Comment by oo12** [comment]
Fixed in v2.2.0.
