### ISSUE TITLE
[Q] Remove hash from generated image and no deletion upon cache clear.

### ISSUE THREAD

**Issue by zaigham** [modxcms/pThumb#6]
Is it possible to not append the "hash" and dont delete the image upon clear cache.

I would like it to make a one time image resizing and keep the copy forever.

**Comment by oo12** [comment]
Yes, that's possible, mostly.

First off, I wouldn't recommend getting rid of the hash in most cases.  If you do, once the thumbnail is generated any further changes you make to the thumbnail options will be ignored until you delete the cache file.  Also you won't be able to use the same image anywhere on the site with different thumbnail options (say, a 150x150 thumbnail and a larger 900x600 version) since both of these would have the same cache filename and the second would never get generated.
If you use the new [pThumb cache](https://github.com/oo12/phpThumbOf#pthumb-cache) the hash will only be 8 characters instead of the previous 32, which makes a big difference visually. That's what I'd recommend.
However, the old phpThumbOf 'Post-fix Properties Hash to Name' setting is still there, so if you decide you _really_ don't want a hash, set that to No (in System Settings) and also set 'Use pThumb Cache' to No.

Then on to cache clearing. At the moment, if the pThumb Cache is never cleared automatically.  If you're using the old style phpThumbOf cache (like to completely get rid of the hash), then this cache is only cleaned on site refresh, i.e. going to Site > Clear Cache in the Manager.  The cleaning is done based on the three 'phpThumb Max Cache *' settings in core / phpThumb in System Settings.  Set all three of these values to 0 and nothing will ever be deleted from the cache.

In the next version I'm going to add a setting for what to do on site refresh: clear, clean, or do nothing. Also I'll make this affect either cache, the new pThumb style cache as well as the “phpThumbOf” version.

Hopefully this explanation isn't too confusing?

**Comment by zaigham** [comment]
It makes complete sense. Thanks for putting up very detailed explanation. :+1: 

I have set phpThumb cache settings to 0, to avoid deletion, and keeping the hash as it is.
