### ISSUE TITLE
useResizer=0 and still won't perform gray filter

### ISSUE THREAD

**Issue by watou** [modxcms/pThumb#7]
When using pThumb 2.0.0-pl, I could successfully use the gray image filter.  Now with 2.1.0-pl2, even if I explicitly set `phpthumbof.use_resizer` to `No` in the MODX System Settings, or pass `&userResizer=0` in the options, I still have the other options work but the fltr[]=gray is not performed.

```
[[+logo:phpthumbof=`&h=40&f=png&fltr[]=gray&useResizer=0`]]
```

**Comment by oo12** [comment]
That last line should be:

```
[[phpthumbof? &input=`[[+logo]]` &options=`h=40&f=png&fltr[]=gray` &useResizer=`0`]]
```

When you use it as an output filter, everything in that string goes to phpThumb/Resizer as options.  `&useResizer` is a property though; if you put it in the options string it won't go to the right place and will get ignored.

About the use_resizer setting, that _should_ be working.  However, make sure the image is not cached before changing it.  If use_resizer was Yes and you did:

```
[[+logo:phpthumbof=`h=40&f=png&fltr[]=gray`]]
```

It would create an image, just ignoring the filter since Resizer doesn't support them.  If you then change the system setting, that will (in theory :-) take effect for new images, but your first image is already cached, so it won't be updated.  After you toggle that setting, try either deleting the cached image or adding something to the options string so a new version will be generated, for example:

```
[[+logo:phpthumbof=`h=40&f=png&fltr[]=gray&bogus=1`]]
```

I might should change things so that separate cached images would be generated for phpThumb and Resizer (i.e. the hash will change depending on which one you're using).  Right now the output from either one will be saved to the same cache name.  I hadn't considered this combination of events...

**Comment by watou** [comment]
Thank you very much for the reply.  I had tried 

```
[[phpthumbof? &input=`[[+logo]]` &options=`h=40&f=png&fltr[]=gray` &useResizer=`0`]]
```

but it made no difference so then I lumped `&useResizer=0` into `&options` knowing that didn't look right.   

In any event, the issue was a cache that wasn't clearing.  I physically deleted the contents of my assets/image-cache directory, cleared the MODX cache, and the `&useResizer=`0`` passed to the snippet now works as hoped.

Thanks again for being so incredibly helpful.

watou

**Comment by watou** [comment]
By the way, it's interesting to use an image shrunk by Resizer as a mouseover image for a gray image that was shrunk by phpthumb (`userResizer=`0``), because it shows how different the scaling algorithms are between the two.

**Comment by oo12** [comment]
Here's a new version which encodes the 'use Resizer' setting / property in the cache filename hash.  That way, if you generate an image one way then toggle the setting, a new image will be generated, without you having to clear any files from the cache.  The only little downside is: now switching the setting will make all your cached images stale and they'll be regenerated (though the old versions will stay in the cache and will be used if you switch the setting back).

If you'd like to test it out, find core/components/phpthumbof/model/phpthumbof.class.php and replace its contents with the [new version](https://raw.github.com/oo12/phpThumbOf/pThumb-dev/core/components/phpthumbof/model/phpthumbof.class.php).

**Comment by watou** [comment]
Thanks very much!  I will test it if you would like me to, but if you're sure there are no problems with it, I will just wait for it to appear in a future release.  Regards, watou

**Comment by oo12** [comment]
I put this change into version 2.2.0.  I think it'll save folks a bit of confusion on occasion.
